### ISSUE TITLE
Error with class `scripts.helloworld.HelloworldPackage` not being found

### ISSUE THREAD

**Issue by mandarg** [andrewoma/kotlin-scripting-kickstarter#3]
I'm having a problem with using this kickstarter environment, and opened an issue to see if you or anyone else might have encountered this.

```
{~/code/kotlin-scripts} (master)$ ./gradlew check copyToLib
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestKotlin
:compileTestJava UP-TO-DATE
:processTestResources
:testClasses
:test
:check
:copyToLib UP-TO-DATE

BUILD SUCCESSFUL

Total time: 8.289 secs
{~/code/kotlin-scripts} (master)$ export PATH=$PATH:`pwd`/kotlin
{~/code/kotlin-scripts} (master)$ helloworld.kt
Error: Could not find or load main class scripts.helloworld.HelloworldPackage
```
I understand this is some sort of problem with the Java `CLASSPATH`, but I wasn't quite able to grok how exactly it is set in this environment. Could you provide any pointers towards debugging this situation?

**Comment by andrewoma** [comment]
Sorry, it seems I haven't updated the script runner to work with the new package structure introduced in 1.0.0-beta.

Kotlin now generates a class called scripts.helloworld.HelloworldKt - I'll try and fix it shortly

**Comment by andrewoma** [comment]
Should be fixed by https://github.com/andrewoma/kotlin-scripting-kickstarter/commit/d7b4ed9c3e36f4e4d2d64887576e7b60e4d82c54

**Comment by mandarg** [comment]
That seems to have fixed it.

Thanks a lot for the fix, and also for the project!

**Comment by andrewoma** [comment]
No worries - I'm glad you found it useful.
