### ISSUE TITLE
put the script runner into gradle

### ISSUE THREAD

**Issue by sandys** [andrewoma/kotlin-scripting-kickstarter#4]
hi,
your kickstarter was the first example of how to use kotlin scripting. Thank you!!

is there a way we can add some targets to the gradle file such that "`gradlew kotlin/helloworld.kt`" will run instead of using a separate .sh file.

this will make the entire usage consistent for all of us - in the way that running it for the first time will complain "dependencies missing. run gradlew copyToLib first", etc.

Also, running any script (like helloworld.kt) induces compilation of ALL kotlin files (like Histogram.kt). Can it not be on demand ? only the scripts that are sourced are run ? I think 1.1-M3 builds in some of that support

thank you so much!

**Comment by andrewoma** [comment]
Hi Sandeep,

You don't need a separate shell script for each script - they can all share `kotlin-script.sh` - it automatically "targets" for you.

I'm not planning on making an other optimisations as this will become redundant when the 1.1 scripting KEEP lands (https://github.com/Kotlin/KEEP/blob/master/proposals/script-definition-template.md).

Cheers,
Andrew
